language: ruby
rvm:
  - 2.5.3

cache:
  directories:
    - vendor/bundler

script:
  - bundle install --path vendor/bundler
  - bundle exec jekyll build -s ./docs

after_success:
  - git config --global user.email 'travis@kamataryo.com'
  - git config --global user.name 'travis bot'
  - openssl aes-256-cbc -K $encrypted_45b4d4f50be1_key -iv $encrypted_45b4d4f50be1_iv -in .travis_rsa.enc -out ./.travis_rsa -d
  - mv ./.travis_rsa $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa
  - bundle exec rake deploy
